### ISSUE TITLE
Incorrect paste behavior, paste causes highlight failure and style errors

### ISSUE THREAD

**Issue by Innei** [KazariEX/plain-shiki#5]
Since this is a contentable element, there is no processing when pasting rich text, and it should only paste plain text.

https://github.com/user-attachments/assets/97803753-69f4-4b8f-b79c-b37bb4667b7c

**Comment by KazariEX** [comment]
The original intention of doing this is to make some rich text in the code work well, because not all browsers support `contenteditable="plaintext-only"`. I'm not sure if manually support this will introduce too much rich text processing code into the library.
